#!/usr/bin/env node
// sync-memory.mjs — distribute the canonical AI-Memory vault rules to every AI agent.
//
// Single source of truth:  <vault>/rules/AGENTS.md  (+ rules/languages/*  + rules/domains/*)
// Run:
//   node sync-memory.mjs                 # write GLOBAL targets (all agents' machine-wide files)
//   node sync-memory.mjs --project PATH  # also drop per-project rule files into a repo + ensure Claude junction
//   node sync-memory.mjs --watch         # re-sync global targets whenever rules/ changes
//   node sync-memory.mjs --dry-run       # show what would change without writing
//
// No external dependencies. Idempotent (only writes when content changes).

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const VAULT = path.resolve(SCRIPT_DIR, '..');
const HOME = os.homedir();
const RULES_DIR = path.join(VAULT, 'rules');
const CONFIG = JSON.parse(fs.readFileSync(path.join(SCRIPT_DIR, 'targets.json'), 'utf8'));

// vault path expressed relative to home, forward-slashed, for Claude @~/ imports
const VAULT_REL = path.relative(HOME, VAULT).split(path.sep).join('/');

const args = process.argv.slice(2);
const DRY = args.includes('--dry-run');
const WATCH = args.includes('--watch');
let projectPath = null;
for (let i = 0; i < args.length; i++) {
  if (args[i] === '--project') projectPath = args[i + 1];
  else if (args[i].startsWith('--project=')) projectPath = args[i].slice('--project='.length);
}

const GEN_MARKER = 'Generated by AI-Memory sync';
const GEN_HEADER = '<!-- ' + GEN_MARKER + '. Do NOT edit here — edit rules in ' + VAULT + ' then re-run scripts/sync-memory.mjs. -->';

// ---------- helpers ----------
function log(msg) { process.stdout.write(msg + '\n'); }

function stripWikilinks(s) {
  return s
    .replace(/!\[\[[^\]]+\]\]/g, '')                       // drop embeds
    .replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, '$2')          // [[target|display]] -> display
    .replace(/\[\[([^\]]+)\]\]/g, (_, t) => t.split('/').pop()); // [[a/b]] -> b
}

function readScoped(subdir) {
  const dir = path.join(RULES_DIR, subdir);
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .sort()
    .map(f => path.join(dir, f));
}

// Canonical rule files in load order: AGENTS.md, then languages/*, then domains/*
function ruleFiles() {
  const out = [];
  const agents = path.join(RULES_DIR, 'AGENTS.md');
  if (fs.existsSync(agents)) out.push(agents);
  return out.concat(readScoped('languages'), readScoped('domains'));
}

// Compiled, agent-ready rules text (concatenated, wikilinks stripped)
function compileRules() {
  const parts = ruleFiles().map(f => fs.readFileSync(f, 'utf8').trim());
  return stripWikilinks(parts.join('\n\n'));
}

function writeIfChanged(target, content) {
  const exists = fs.existsSync(target);
  const current = exists ? fs.readFileSync(target, 'utf8') : null;
  if (current === content) { log(`  = unchanged  ${target}`); return; }
  // Safety: never clobber a hand-authored file (one we didn't generate).
  if (exists && current !== null && !current.includes(GEN_MARKER)) {
    log(`  ! SKIP (not ours — hand-authored) ${target}`);
    return;
  }
  if (DRY) { log(`  ~ would write ${target}`); return; }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content, 'utf8');
  log(`  ${exists ? '* updated' : '+ created'}  ${target}`);
}

function renderTarget(mode, opts = {}) {
  const compiled = compileRules();
  switch (mode) {
    case 'plain': {
      let body = `${GEN_HEADER}\n\n${compiled}\n`;
      if (opts.maxChars && body.length > opts.maxChars) {
        const keep = opts.maxChars - GEN_HEADER.length - 40;
        body = `${GEN_HEADER}\n\n${compiled.slice(0, Math.max(0, keep))}\n\n<!-- TRUNCATED to ${opts.maxChars} chars -->\n`;
        log(`  ! truncated to ${opts.maxChars} chars (full rules are longer) for ${opts.agent}`);
      }
      return body;
    }
    case 'mdc':
      return `---\ndescription: Global rules (synced from AI-Memory vault)\nalwaysApply: true\n---\n\n${GEN_HEADER}\n\n${compiled}\n`;
    case 'kiro':
      return `---\ninclusion: always\n---\n\n${GEN_HEADER}\n\n${compiled}\n`;
    case 'import-line':
      // project CLAUDE.md -> import sibling AGENTS.md
      return `${GEN_HEADER}\n@${opts.import}\n`;
    case 'claude-global': {
      // ~/.claude/CLAUDE.md -> live @-imports of each vault rule file (content edits are live;
      // adding a NEW scoped file needs a re-sync to add its import line)
      const lines = ruleFiles().map(f => {
        const rel = path.relative(VAULT, f).split(path.sep).join('/');
        return `@~/${VAULT_REL}/${rel}`;
      });
      return `${GEN_HEADER}\n# AI-Memory global rules (auto-imported from the Obsidian vault)\n${lines.join('\n')}\n`;
    }
    default:
      throw new Error(`unknown mode: ${mode}`);
  }
}

// ---------- global ----------
function syncGlobal() {
  log('Global targets:');
  for (const t of CONFIG.globalTargets) {
    const target = path.join(HOME, t.homePath);
    writeIfChanged(target, renderTarget(t.mode, { maxChars: t.maxChars, agent: t.agent }));
  }
}

// ---------- per-project ----------
function projectSlug(absPath) {
  // Claude derives the slug by replacing EACH drive/separator char with '-' (so "C:\" -> "C--").
  return absPath.replace(/[\\/:]/g, '-');
}

function findClaudeProjectDir(absPath) {
  const projectsDir = path.join(HOME, '.claude', 'projects');
  if (!fs.existsSync(projectsDir)) return null;
  const wanted = projectSlug(absPath).toLowerCase();
  for (const name of fs.readdirSync(projectsDir)) {
    if (name.toLowerCase() === wanted) return path.join(projectsDir, name);
  }
  return null;
}

function ensureClaudeJunction(absPath) {
  const projName = path.basename(absPath);
  const vaultMem = path.join(VAULT, 'projects', projName, 'memory');
  const slugDir = findClaudeProjectDir(absPath);
  if (!slugDir) {
    log(`  i Claude has no project dir for "${absPath}" yet — open it in Claude Code once, then re-run --project.`);
    return;
  }
  const claudeMem = path.join(slugDir, 'memory');
  // Already a junction/symlink?
  try {
    if (fs.existsSync(claudeMem) && fs.lstatSync(claudeMem).isSymbolicLink()) {
      log(`  = junction already set  ${claudeMem}`);
      return;
    }
  } catch {}
  const hasFiles = fs.existsSync(claudeMem) && fs.readdirSync(claudeMem).length > 0;
  if (hasFiles) {
    log(`  ! ${claudeMem} contains files — run link-claude-project.ps1 to migrate safely (won't auto-move here).`);
    return;
  }
  if (DRY) { log(`  ~ would junction ${claudeMem} -> ${vaultMem}`); return; }
  fs.mkdirSync(vaultMem, { recursive: true });
  if (fs.existsSync(claudeMem)) fs.rmdirSync(claudeMem);
  fs.symlinkSync(vaultMem, claudeMem, 'junction');   // 'junction' = no admin needed on Windows
  log(`  + junction ${claudeMem} -> ${vaultMem}`);
}

function syncProject(absPath) {
  const root = path.resolve(absPath);
  if (!fs.existsSync(root)) { log(`! project path does not exist: ${root}`); return; }
  log(`Project targets (${root}):`);
  for (const t of CONFIG.projectTargets) {
    const target = path.join(root, t.rel);
    writeIfChanged(target, renderTarget(t.mode, { import: t.import, maxChars: t.maxChars, agent: t.agent }));
  }
  log('Claude memory junction:');
  ensureClaudeJunction(root);
}

// ---------- run ----------
function runOnce() {
  log(`AI-Memory sync  (vault: ${VAULT})${DRY ? '  [dry-run]' : ''}`);
  syncGlobal();
  if (projectPath) syncProject(projectPath);
}

runOnce();

if (WATCH) {
  log(`\nWatching ${RULES_DIR} for changes (Ctrl+C to stop)...`);
  let timer = null;
  fs.watch(RULES_DIR, { recursive: true }, () => {
    clearTimeout(timer);
    timer = setTimeout(() => { log('\n-- change detected, re-syncing --'); syncGlobal(); }, 250);
  });
}
